# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
# fos_rest: null
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception: 
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }

fos_rest:
    param_fetcher_listener:         force
    body_listener:                  true
    allowed_methods_listener:       true
    unauthorized_challenge:         "Basic realm=\"Restricted Area\""
    access_denied_listener:
        json:                       true
        xml:                        true
        html:                       true

    routing_loader:
        include_format:             false

    view:
        view_response_listener:     force
        force_redirects:
          html:                     true
        formats:
            json:                   true
            xml:                    true

    format_listener:
        rules:
            - { path: ^/, fallback_format: json, priorities: [ json ] }