fos_oauth_server:
    db_driver:                  orm
    client_class:               App\Entity\Client
    access_token_class:         App\Entity\AccessToken
    refresh_token_class:        App\Entity\RefreshToken
    auth_code_class:            App\Entity\AuthCode

    authorize:
        form:
            type:               fos_oauth_server_authorize
            handler:            fos_oauth_server.authorize.form.handler.default
            name:               fos_oauth_server_authorize_form
            validation_groups:
                - Authorize
                - Default

    service:
        storage:                fos_oauth_server.storage.default
        user_provider:          fos_user.user_provider.username_email
        client_manager:         fos_oauth_server.client_manager.default
        access_token_manager:   fos_oauth_server.access_token_manager.default
        refresh_token_manager:  fos_oauth_server.refresh_token_manager.default
        auth_code_manager:      fos_oauth_server.auth_code_manager.default
        options:
            access_token_lifetime: 2592000
            refresh_token_lifetime: 2592000
            auth_code_lifetime: 30
    template:
        engine:                 twig
